services:

  postgres:
    image: postgres:17
    container_name: creator_postgres

    restart: unless-stopped

    ports:
      - "5434:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - creator_network

  redis:
    image: redis:8

    container_name: creator_redis

    restart: unless-stopped

    ports:
      - "6380:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test:
        [
          "CMD",
          "redis-cli",
          "ping"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - creator_network

  pgadmin:
    image: dpage/pgadmin4

    container_name: creator_pgadmin

    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

    ports:
      - "5050:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    networks:
      - creator_network

volumes:

  postgres_data:

  redis_data:

  pgadmin_data:

networks:

  creator_network:
    driver: bridge